import type { Metadata } from 'next'
import '@/styles/globals.scss'
import { msFont } from '@/styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={msFont.className}>{children}</body>
    </html>
  )
}
